name: Documentation
on:
  push:
    tags:
      - "*"
    branches: [main, master]
permissions:
  contents: read
jobs:
  build:
    name: Build and publish documentation
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update
      - name: Setup Cpp
        uses: aminya/setup-cpp@8170d66c458f4a045220b7b0966c10940bb2a15d # v1.8.1
        with:
          clangtidy: true
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Install Docs
        run: |
          sudo apt-get install doxygen
          pip install -r requirements.txt  --require-hashes
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
      - name: building
        run: |
          cmake --build build --config Debug --target doc_doxygen -j4
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@502048fbc429a8ac1d1823976874aa4e5be155fb # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./build/docs/doc_doxygen/html
