name: Windows CI Test
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: configure
        run: |
          cmake -H"." -Bbuild -T host=x86 -A x64 -DCMAKE_BUILD_TYPE="Debug"
      - name: building
        run: |
          cmake --build build --config Debug --target Catch_tests_run -j4
      - name: run unit tests
        run: |
          cd build
          cd bin
          cd Debug
          .\Catch_tests_run.exe
